import { db } from '@/db';
import { donations } from '@/db/schema';

async function main() {
    const sampleDonations = [
        {
            donorName: 'Priya Sharma',
            contactNumber: '9876543210',
            donationType: 'Goods/Items',
            itemName: 'Silk Saree Collection',
            category: 'Clothing',
            condition: 'Like New',
            description: 'Beautiful collection of 3 silk sarees in excellent condition. Includes one Kanjivaram saree, one Banarasi saree, and one South silk saree. All are barely worn, purchased from reputable stores. Perfect for festivals and special occasions. Each saree comes with matching blouse pieces.',
            photoUrls: JSON.stringify(['https://example.com/saree1.jpg', 'https://example.com/saree2.jpg', 'https://example.com/saree3.jpg']),
            location: 'Bandra West, Mumbai',
            contactEmail: 'priya.sharma@gmail.com',
            contactPhone: '8765432109',
            status: 'available',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            donorName: 'Rajesh Kumar',
            contactNumber: '8765432109',
            donationType: 'Goods/Items',
            itemName: 'Cotton Kurta Set',
            category: 'Clothing',
            condition: 'Good',
            description: 'Men\'s cotton kurta pajama set, size L. Light blue color with white pajama. Comfortable fabric, suitable for daily wear or casual occasions. Washed and well-maintained. Minor signs of wear but still in good condition.',
            photoUrls: JSON.stringify(['https://example.com/kurta1.jpg', 'https://example.com/kurta2.jpg']),
            location: 'Connaught Place, New Delhi',
            contactEmail: 'rajesh.kumar@yahoo.com',
            contactPhone: null,
            status: 'claimed',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            donorName: 'Meera Nair',
            contactNumber: '7654321098',
            donationType: 'Goods/Items',
            itemName: 'Teak Wood Study Table',
            category: 'Furniture',
            condition: 'Good',
            description: 'Solid teak wood study table with 3 drawers. Dimensions: 4ft x 2ft x 2.5ft height. Perfect for students or home office use. Some minor scratches on the surface but structurally very strong. Includes a comfortable wooden chair. Moving house, hence selling.',
            photoUrls: JSON.stringify(['https://example.com/table1.jpg', 'https://example.com/table2.jpg']),
            location: 'Koramangala, Bangalore',
            contactEmail: 'meera.nair@hotmail.com',
            contactPhone: '6543210987',
            status: 'available',
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            donorName: 'Amit Patel',
            contactNumber: '9543210987',
            donationType: 'Goods/Items',
            itemName: 'L-Shaped Sofa Set',
            category: 'Furniture',
            condition: 'Fair',
            description: 'Brown leather L-shaped sofa set, seats 6 people comfortably. Shows signs of regular use but still functional and comfortable. Some wear on armrests and cushions need re-stuffing. Great for large families or community spaces. Buyer needs to arrange pickup.',
            photoUrls: JSON.stringify(['https://example.com/sofa1.jpg']),
            location: 'Satellite, Ahmedabad',
            contactEmail: 'amit.patel@gmail.com',
            contactPhone: '8432109876',
            status: 'available',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            donorName: 'Sanjay Reddy',
            contactNumber: '8432109876',
            donationType: 'Goods/Items',
            itemName: 'Samsung Galaxy S21',
            category: 'Electronics',
            condition: 'Like New',
            description: 'Samsung Galaxy S21 5G, 128GB storage, Phantom Gray color. Excellent condition with original box, charger, and earphones. Screen protector and case applied since day one. Battery health is excellent. Upgraded to newer model, hence donating.',
            photoUrls: JSON.stringify(['https://example.com/phone1.jpg', 'https://example.com/phone2.jpg']),
            location: 'HITEC City, Hyderabad',
            contactEmail: 'sanjay.reddy@outlook.com',
            contactPhone: null,
            status: 'available',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            donorName: 'Kavita Singh',
            contactNumber: '7321098765',
            donationType: 'Goods/Items',
            itemName: 'Dell Laptop',
            category: 'Electronics',
            condition: 'Good',
            description: 'Dell Inspiron 15 laptop, Intel i5 processor, 8GB RAM, 256GB SSD. Good working condition, suitable for office work, studies, and light gaming. Battery lasts 4-5 hours. Comes with original charger and laptop bag. Minor scratches on the lid.',
            photoUrls: JSON.stringify(['https://example.com/laptop1.jpg']),
            location: 'Salt Lake, Kolkata',
            contactEmail: 'kavita.singh@gmail.com',
            contactPhone: '6210987654',
            status: 'claimed',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            donorName: 'Ravi Iyer',
            contactNumber: '9210987654',
            donationType: 'Goods/Items',
            itemName: 'NCERT Textbook Set',
            category: 'Books',
            condition: 'Good',
            description: 'Complete set of NCERT textbooks for Class 12 Science stream (Physics, Chemistry, Biology, Mathematics). All books are in good condition with minimal highlighting and notes. Perfect for students preparing for board exams or competitive entrance tests.',
            photoUrls: JSON.stringify(['https://example.com/books1.jpg', 'https://example.com/books2.jpg']),
            location: 'T. Nagar, Chennai',
            contactEmail: 'ravi.iyer@yahoo.in',
            contactPhone: '8109876543',
            status: 'available',
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            donorName: 'Anjali Gupta',
            contactNumber: '8109876543',
            donationType: 'Goods/Items',
            itemName: 'Harry Potter Book Series',
            category: 'Books',
            condition: 'Like New',
            description: 'Complete Harry Potter series (7 books) in excellent condition. Hardcover editions with dust jackets intact. Perfect for young readers or Harry Potter fans. Books have been well-maintained and stored properly. Great addition to any personal or community library.',
            photoUrls: JSON.stringify(['https://example.com/harrypotter1.jpg']),
            location: 'Civil Lines, Jaipur',
            contactEmail: 'anjali.gupta@rediffmail.com',
            contactPhone: null,
            status: 'completed',
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            donorName: 'Suresh Joshi',
            contactNumber: '7098765432',
            donationType: 'Goods/Items',
            itemName: 'Preethi Mixer Grinder',
            category: 'Kitchen',
            condition: 'Good',
            description: 'Preethi Blue Leaf Diamond 3-jar mixer grinder, 750W motor. Excellent grinding performance for wet and dry ingredients. Includes all original jars and accessories. Some minor wear on the body but motor works perfectly. Great for Indian cooking needs.',
            photoUrls: JSON.stringify(['https://example.com/mixer1.jpg', 'https://example.com/mixer2.jpg']),
            location: 'Shivaji Nagar, Pune',
            contactEmail: 'suresh.joshi@gmail.com',
            contactPhone: '9987654321',
            status: 'available',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            donorName: 'Deepika Mehta',
            contactNumber: '6987654321',
            donationType: 'Goods/Items',
            itemName: 'Hawkins Pressure Cooker Set',
            category: 'Kitchen',
            condition: 'Like New',
            description: 'Set of 2 Hawkins pressure cookers - 3L and 5L capacity. Barely used, like new condition with all safety features intact. Includes original whistle, gasket, and user manual. Perfect for small to medium families. Excellent build quality and performance.',
            photoUrls: JSON.stringify(['https://example.com/pressure1.jpg']),
            location: 'Indore',
            contactEmail: 'deepika.mehta@hotmail.com',
            contactPhone: '8876543210',
            status: 'available',
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            donorName: 'Manoj Agarwal',
            contactNumber: '8876543210',
            donationType: 'Goods/Items',
            itemName: 'Cricket Kit Complete Set',
            category: 'Sports',
            condition: 'Good',
            description: 'Complete cricket kit including SG bat (size 6), helmet, pads, gloves, thigh guard, and kitbag. Suitable for teenagers or young adults. Bat has some scuff marks but still in playing condition. All protective gear is well-maintained. Perfect for cricket enthusiasts.',
            photoUrls: JSON.stringify(['https://example.com/cricket1.jpg', 'https://example.com/cricket2.jpg']),
            location: 'Lajpat Nagar, New Delhi',
            contactEmail: 'manoj.agarwal@yahoo.com',
            contactPhone: null,
            status: 'available',
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            donorName: 'Pooja Bansal',
            contactNumber: '7765432109',
            donationType: 'Goods/Items',
            itemName: 'Badminton Racket Pair',
            category: 'Sports',
            condition: 'New',
            description: 'Brand new pair of Yonex badminton rackets with covers and a set of shuttlecocks. Never used, still in original packaging. Received as gifts but already have rackets. Perfect for beginners or intermediate players. Includes instruction manual.',
            photoUrls: JSON.stringify(['https://example.com/badminton1.jpg']),
            location: 'Model Town, Ludhiana',
            contactEmail: 'pooja.bansal@gmail.com',
            contactPhone: '6654321098',
            status: 'claimed',
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            donorName: 'Arjun Das',
            contactNumber: '9654321098',
            donationType: 'Goods/Items',
            itemName: 'Educational Board Games',
            category: 'Toys & Other',
            condition: 'Like New',
            description: 'Collection of educational board games including Scrabble, Monopoly, and Chess set. All games are complete with original pieces and instructions. Great for family time and developing strategic thinking in children. Barely used, excellent condition.',
            photoUrls: JSON.stringify(['https://example.com/games1.jpg', 'https://example.com/games2.jpg']),
            location: 'Park Street, Kolkata',
            contactEmail: 'arjun.das@outlook.com',
            contactPhone: '5543210987',
            status: 'available',
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            donorName: 'Nisha Pillai',
            contactNumber: '8543210987',
            donationType: 'Goods/Items',
            itemName: 'Art Supplies Set',
            category: 'Toys & Other',
            condition: 'Good',
            description: 'Complete art supplies set including watercolors, oil pastels, sketching pencils, brushes, canvas boards, and drawing books. Some items are partially used but plenty left for creative projects. Perfect for art students or hobby artists.',
            photoUrls: JSON.stringify(['https://example.com/art1.jpg']),
            location: 'Kochi',
            contactEmail: 'nisha.pillai@rediffmail.com',
            contactPhone: '7432109876',
            status: 'available',
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            donorName: 'Vikram Chawla',
            contactNumber: '7432109876',
            donationType: 'Monetary',
            itemName: 'Education Fund Donation',
            category: 'Books',
            condition: 'New',
            description: 'Monetary donation of ₹15,000 specifically for purchasing educational books and study materials for underprivileged children. Can be used for textbooks, notebooks, stationery, or digital learning resources. Prefer donation to go towards primary or secondary education.',
            photoUrls: JSON.stringify([]),
            location: 'Sector 18, Noida',
            contactEmail: 'vikram.chawla@gmail.com',
            contactPhone: null,
            status: 'available',
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            donorName: 'Sunita Rao',
            contactNumber: '6321098765',
            donationType: 'Monetary',
            itemName: 'Kitchen Equipment Fund',
            category: 'Kitchen',
            condition: 'New',
            description: 'Monetary contribution of ₹8,500 for purchasing kitchen equipment for community kitchens or families in need. Can be used for basic cooking utensils, gas stove, or small appliances. Prefer transparent usage and acknowledgment of how funds are utilized.',
            photoUrls: JSON.stringify([]),
            location: 'Jayanagar, Bangalore',
            contactEmail: 'sunita.rao@yahoo.in',
            contactPhone: '9210987654',
            status: 'claimed',
            createdAt: new Date('2024-03-03').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        {
            donorName: 'Rohit Malhotra',
            contactNumber: '8210987654',
            donationType: 'Volunteer Time',
            itemName: 'Mathematics Tutoring Sessions',
            category: 'Books',
            condition: 'New',
            description: 'Offering 15 hours of volunteer time per month for teaching mathematics to students from Class 6 to Class 12. Can help with homework, exam preparation, and concept clarification. Available on weekends and weekday evenings. Engineering graduate with passion for teaching.',
            photoUrls: JSON.stringify([]),
            location: 'Gurgaon',
            contactEmail: 'rohit.malhotra@gmail.com',
            contactPhone: '7109876543',
            status: 'available',
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            donorName: 'Lakshmi Narayan',
            contactNumber: '9109876543',
            donationType: 'Volunteer Time',
            itemName: 'Clothing Repair Services',
            category: 'Clothing',
            condition: 'New',
            description: 'Offering tailoring and clothing repair services as volunteer work. Can mend torn clothes, resize garments, and basic alterations. Available 10 hours per week, preferably for families or individuals who cannot afford professional tailoring services. 15+ years experience.',
            photoUrls: JSON.stringify([]),
            location: 'Mylapore, Chennai',
            contactEmail: 'lakshmi.narayan@hotmail.com',
            contactPhone: '8009876543',
            status: 'available',
            createdAt: new Date('2024-03-07').toISOString(),
            updatedAt: new Date('2024-03-07').toISOString(),
        }
    ];

    await db.insert(donations).values(sampleDonations);
    
    console.log('✅ Donations seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});